version: "3"

services:
  octochainbackend:
    container_name: octochain_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8006:8006"
    volumes:
      - .:/octochain
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8006"
    environment:
      - DB_HOST=db
      - DB_NAME=octochain
      - DB_USER=postgres
      - DB_PASS=testpassword
    depends_on:
      - db

  db:
    container_name: octochain_postgres
    image: postgres:15-alpine
    command: postgres -c shared_buffers=256MB -c max_connections=200
    environment:
      - POSTGRES_DB=octochain
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    container_name: octochain_cache
    image: redis
    command: --port 6390
    ports:
      - "6390:6390"
    expose:
      - "6390"

volumes:
  db:
