# Generated by Django 4.1.5 on 2023-12-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
