# Generated by Django 4.1.5 on 2023-12-25 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hedge_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HedgeBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.CharField(max_length=255)),
                ('exchanges', models.JSONField()),
                ('settings', models.JSONField()),
                ('status', models.BooleanField(default=False)),
                ('max_size', models.IntegerField(default=1000)),
                ('control_size', models.IntegerField(default=50)),
                ('tx_size', models.IntegerField(default=40)),
                ('min_profit', models.FloatField(default=0.01)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HedgeBotTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], max_length=255)),
                ('spot_price', models.FloatField()),
                ('hedge_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('profit', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hedge_bot.hedgebot')),
                ('hedge_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hedge_exchange', to='hedge_bot.exchange')),
                ('spot_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_exchange', to='hedge_bot.exchange')),
            ],
        ),
    ]
