# Generated by Django 4.1.5 on 2023-12-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge_bot', '0002_hedgebot_hedgebottx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hedgebottx',
            old_name='quantity',
            new_name='hedge_quantity',
        ),
        migrations.AddField(
            model_name='hedgebottx',
            name='spot_quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
