# Generated by Django 4.1.5 on 2023-12-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hedge_bot', '0003_rename_quantity_hedgebottx_hedge_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hedgebottx',
            old_name='profit',
            new_name='fee',
        ),
    ]
