# Generated by Django 4.1.5 on 2023-12-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge_bot', '0004_rename_profit_hedgebottx_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hedgebot',
            old_name='min_profit',
            new_name='min_open_profit',
        ),
        migrations.AddField(
            model_name='hedgebot',
            name='min_close_profit',
            field=models.FloatField(default=0.005),
        ),
    ]
