# Generated by Django 4.1.5 on 2023-12-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge_bot', '0005_rename_min_profit_hedgebot_min_open_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgebottx',
            name='hedge_cost_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hedgebottx',
            name='spot_cost_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hedgebottx',
            name='hedge_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hedgebottx',
            name='spot_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
