# Generated by Django 4.1.5 on 2023-12-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge_bot', '0007_exchange_future_exchange_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
