# Generated by Django 4.1.5 on 2024-01-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hedge_bot', '0009_hedgebotblacklist'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hedgebot',
            constraint=models.UniqueConstraint(condition=models.Q(('status', True)), fields=('user', 'tick'), name='unique_active_tick_per_user'),
        ),
    ]
